"""empty message

Revision ID: 188bc5320726
Revises: 3603030cc07d
Create Date: 2026-05-07 22:12:43.575105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '188bc5320726'
down_revision: Union[str, Sequence[str], None] = '3603030cc07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'room_type',
               existing_type=postgresql.ENUM('family', 'single', 'double', 'luxury', name='roomtype'),
               nullable=True)
    op.alter_column('room', 'room_status',
               existing_type=postgresql.ENUM('free', 'booked', name='roomstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'room_status',
               existing_type=postgresql.ENUM('free', 'booked', name='roomstatus'),
               nullable=False)
    op.alter_column('room', 'room_type',
               existing_type=postgresql.ENUM('family', 'single', 'double', 'luxury', name='roomtype'),
               nullable=False)
    # ### end Alembic commands ###
