"""empty message

Revision ID: 26c604d0f1f0
Revises: e31e8bfe8daf
Create Date: 2026-05-07 22:18:02.201033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c604d0f1f0'
down_revision: Union[str, Sequence[str], None] = 'e31e8bfe8daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'room_name',
               existing_type=sa.SMALLINT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'room_name',
               existing_type=sa.String(length=32),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
