"""empty message

Revision ID: e31e8bfe8daf
Revises: 188bc5320726
Create Date: 2026-05-07 22:17:25.296533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e31e8bfe8daf'
down_revision: Union[str, Sequence[str], None] = '188bc5320726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'room_type')
    op.drop_column('room', 'room_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_status', postgresql.ENUM('free', 'booked', name='roomstatus'), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('room_type', postgresql.ENUM('family', 'single', 'double', 'luxury', name='roomtype'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
